"""
Alert Management Service.

Provides CRUD operations and filtered/paginated retrieval for
security alerts generated by the anomaly-detection pipeline.
"""

import logging
from typing import Optional
from uuid import uuid4

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from backend.models.alert import Alert
from backend.schemas.alert import AlertCreate

logger = logging.getLogger(__name__)


async def create_alert(db: AsyncSession, alert_data: AlertCreate) -> Alert:
    """
    Create a new security alert.

    Args:
        db: Async database session.
        alert_data: Validated alert creation payload.

    Returns:
        The persisted Alert record.
    """
    logger.info("Creating alert — type=%s, severity=%s", alert_data.attack_type, alert_data.severity)

    alert = Alert(
        id=str(uuid4()),
        title=alert_data.title,
        description=alert_data.description,
        severity=alert_data.severity,
        status="open",
        attack_type=alert_data.attack_type,
        source_ip=getattr(alert_data, "source_ip", None),
        destination_ip=getattr(alert_data, "destination_ip", None),
        confidence=getattr(alert_data, "confidence", None),
        log_entry_id=getattr(alert_data, "log_entry_id", None),
    )

    db.add(alert)
    await db.commit()
    await db.refresh(alert)

    logger.info("Alert created: id=%s", alert.id)
    return alert


async def get_alerts(
    db: AsyncSession,
    page: int = 1,
    page_size: int = 50,
    severity: Optional[str] = None,
    status: Optional[str] = None,
    attack_type: Optional[str] = None,
) -> tuple[list[Alert], int]:
    """
    Retrieve alerts with pagination and optional filters.

    Args:
        db: Async database session.
        page: 1-indexed page number.
        page_size: Number of records per page.
        severity: Optional severity filter (e.g. "critical", "high").
        status: Optional status filter (e.g. "open", "closed").
        attack_type: Optional attack-type filter (e.g. "DoS", "DDoS").

    Returns:
        A tuple of (list_of_alerts, total_count).
    """
    logger.debug(
        "Fetching alerts — page=%d, size=%d, severity=%s, status=%s, attack=%s",
        page, page_size, severity, status, attack_type,
    )

    # ── Build dynamic filters ──────────────────────────────────────────
    conditions = []
    if severity:
        conditions.append(Alert.severity == severity)
    if status:
        conditions.append(Alert.status == status)
    if attack_type:
        conditions.append(Alert.attack_type == attack_type)

    # ── Total count ────────────────────────────────────────────────────
    count_stmt = select(func.count(Alert.id))
    for cond in conditions:
        count_stmt = count_stmt.where(cond)
    total = (await db.execute(count_stmt)).scalar() or 0

    # ── Paginated results ──────────────────────────────────────────────
    offset = (page - 1) * page_size
    query = (
        select(Alert)
        .order_by(Alert.created_at.desc())
        .offset(offset)
        .limit(page_size)
    )
    for cond in conditions:
        query = query.where(cond)

    result = await db.execute(query)
    alerts = list(result.scalars().all())

    logger.debug("Returning %d alerts (total=%d)", len(alerts), total)
    return alerts, total


async def get_alert_by_id(db: AsyncSession, alert_id: str) -> Optional[Alert]:
    """
    Retrieve a single alert by its UUID.

    Args:
        db: Async database session.
        alert_id: UUID string of the alert.

    Returns:
        The matching Alert, or None.
    """
    stmt = select(Alert).where(Alert.id == alert_id)
    result = await db.execute(stmt)
    return result.scalars().first()


async def update_alert(
    db: AsyncSession,
    alert_id: str,
    update_data: dict,
) -> Optional[Alert]:
    """
    Update one or more fields on an existing alert.

    Args:
        db: Async database session.
        alert_id: UUID string of the alert to update.
        update_data: Dictionary of field names → new values.

    Returns:
        The updated Alert, or None if not found.
    """
    logger.info("Updating alert %s with fields: %s", alert_id, list(update_data.keys()))

    alert = await get_alert_by_id(db, alert_id)
    if alert is None:
        logger.warning("Alert not found: %s", alert_id)
        return None

    stmt = (
        update(Alert)
        .where(Alert.id == alert_id)
        .values(**update_data)
    )
    await db.execute(stmt)
    await db.commit()
    await db.refresh(alert)

    logger.info("Alert updated: %s", alert_id)
    return alert


async def delete_alert(db: AsyncSession, alert_id: str) -> bool:
    """
    Delete an alert by its UUID.

    Args:
        db: Async database session.
        alert_id: UUID string of the alert to delete.

    Returns:
        True if the alert was deleted, False if not found.
    """
    logger.info("Deleting alert: %s", alert_id)

    alert = await get_alert_by_id(db, alert_id)
    if alert is None:
        logger.warning("Alert not found for deletion: %s", alert_id)
        return False

    await db.delete(alert)
    await db.commit()

    logger.info("Alert deleted: %s", alert_id)
    return True
